# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_SPN_CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_SPN_CLIENT_SECRET }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_SPN_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_ACCESS_KEY: "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
      TF_VAR_image_registry_username: "${{ secrets.IMAGE_REGISTRY_USERNAME }}"
      TF_VAR_image_registry_password: "${{ secrets.IMAGE_REGISTRY_PASSWORD }}"
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=2425-B2C6-B2B-2" \
            -backend-config="storage_account_name=b2b2tfstatestorage" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Import
        run: |
          terraform import azurerm_resource_group.rg "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/2425-B2C6-B2B-2"
          terraform import azurerm_container_registry.acr "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/2425-B2C6-B2B-2/providers/Microsoft.ContainerRegistry/registries/containerRegistryB2B"

        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Cleanup
        run: rm tfplan 
